#!/usr/bin/env python3
"""Generate Wright package-manager distribution metadata (#108).

Rewrites dist/ with the Homebrew formula, WinGet manifests, and Scoop
manifest for a Wright version. All generated manifests consume the canonical
GitHub Release archives (`wright-<version>-<target>.<ext>` + `.sha256`)
produced by the release workflow; nothing here rebuilds Wright.

Hashes are supplied per platform; missing or zero hashes are rendered as
all-zero placeholders (the state dist/ ships in between releases). CI keeps
the checked-in dist/ in sync via scripts/verify-dist.py.

Usage:
  python3 scripts/update-dist-manifests.py --version 0.1.0 \\
      [--linux-x64-hash H] [--darwin-arm64-hash H] [--darwin-x64-hash H] \\
      [--windows-x64-hash H] [--out-dir DIR]

The release workflow runs this against the published release checksums and
attaches the generated files to the Release (see docs/release.md).
"""

import argparse
import re
import shutil
from pathlib import Path

RELEASE_BASE = "https://github.com/wrightkit/wright/releases/download"
REPO_ROOT = Path(__file__).resolve().parent.parent
PLACEHOLDER_HASH = "0" * 64

# Canonical release matrix; keys match the release workflow target triples.
TARGETS = {
    "linux-x64": "x86_64-unknown-linux-gnu",
    "darwin-arm64": "aarch64-apple-darwin",
    "darwin-x64": "x86_64-apple-darwin",
    "windows-x64": "x86_64-pc-windows-msvc",
}
ARCHIVE_EXT = {
    "x86_64-unknown-linux-gnu": "tar.gz",
    "aarch64-apple-darwin": "tar.gz",
    "x86_64-apple-darwin": "tar.gz",
    "x86_64-pc-windows-msvc": "zip",
}


def valid_hash(value: str) -> bool:
    return bool(re.fullmatch(r"[0-9a-fA-F]{64}", value))


def artifact_url(version: str, triple: str) -> str:
    ext = ARCHIVE_EXT[triple]
    return f"{RELEASE_BASE}/v{version}/wright-{version}-{triple}.{ext}"


def version_from_tag(tag: str) -> str:
    return tag[1:] if tag.startswith("v") else tag


def homebrew_formula(version: str, hashes: dict) -> str:
    arm_url = artifact_url(version, TARGETS["darwin-arm64"])
    x64_url = artifact_url(version, TARGETS["darwin-x64"])
    return f"""# Generated by scripts/update-dist-manifests.py for Wright {version}.
# Consumes the canonical macOS release archives; do not edit by hand.
class Wright < Formula
  desc "Tooling-first semantic platform for the Overwatch Workshop and OverPy ecosystem"
  homepage "https://github.com/wrightkit/wright"
  license "AGPL-3.0-or-later"
  version "{version}"

  on_arm do
    url "{arm_url}"
    sha256 "{hashes["darwin-arm64"]}"
  end

  on_intel do
    url "{x64_url}"
    sha256 "{hashes["darwin-x64"]}"
  end

  def install
    dir = "wright-#{{version}}-#{{Hardware::CPU.arm? ? "aarch64-apple-darwin" : "x86_64-apple-darwin"}}"
    bin.install "#{{dir}}/wright"
    bin.install "#{{dir}}/wright-lsp"
  end

  test do
    assert_match version.to_s, shell_output("#{{bin}}/wright --version")
    assert_match version.to_s, shell_output("#{{bin}}/wright-lsp --version")
  end
end
"""


def winget_installer(version: str, windows_hash: str) -> str:
    win_url = artifact_url(version, TARGETS["windows-x64"])
    payload = f"wright-{version}-x86_64-pc-windows-msvc"
    return f"""# Generated by scripts/update-dist-manifests.py for Wright {version}.
# The canonical Windows release ZIP (a zip of portable executables).
PackageIdentifier: WrightKit.Wright
PackageVersion: {version}
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: {payload}/wright.exe
    PortableCommandAlias: wright
  - RelativeFilePath: {payload}/wright-lsp.exe
    PortableCommandAlias: wright-lsp
Installers:
  - Architecture: x64
    InstallerUrl: {win_url}
    InstallerSha256: {windows_hash}
    Scope: user
    ElevationRequirement: elevationProhibited
ManifestType: installer
ManifestVersion: 1.12.0
"""


def winget_default_locale(version: str) -> str:
    return f"""# Generated by scripts/update-dist-manifests.py for Wright {version}.
PackageIdentifier: WrightKit.Wright
PackageVersion: {version}
PackageLocale: en-US
Publisher: WrightKit
PublisherUrl: https://github.com/wrightkit
PublisherSupportUrl: https://github.com/wrightkit/wright/issues
PackageName: Wright
PackageUrl: https://github.com/wrightkit/wright
License: AGPL-3.0-or-later
LicenseUrl: https://github.com/wrightkit/wright/blob/main/LICENSE
ShortDescription: Tooling-first semantic platform for the Overwatch Workshop and OverPy ecosystem.
Tags:
  - overwatch
  - workshop
  - overpy
  - compiler
  - language-server
  - cli
Moniker: wright
ManifestType: defaultLocale
ManifestVersion: 1.12.0
"""


def winget_version(version: str) -> str:
    return f"""# Generated by scripts/update-dist-manifests.py for Wright {version}.
PackageIdentifier: WrightKit.Wright
PackageVersion: {version}
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.12.0
"""


def scoop_manifest(version: str, windows_hash: str) -> str:
    win_url = artifact_url(version, TARGETS["windows-x64"])
    payload = f"wright-{version}-x86_64-pc-windows-msvc"
    return f"""{{
  "version": "{version}",
  "description": "Tooling-first semantic platform for the Overwatch Workshop and OverPy ecosystem",
  "homepage": "https://github.com/wrightkit/wright",
  "license": "AGPL-3.0-or-later",
  "architecture": {{
    "64bit": {{
      "url": "{win_url}",
      "hash": "{windows_hash}",
      "extract_dir": "{payload}"
    }}
  }},
  "bin": [
    "wright.exe",
    "wright-lsp.exe"
  ],
  "checkver": {{
    "github": "https://github.com/wrightkit/wright"
  }},
  "autoupdate": {{
    "extract_dir": "wright-$version-x86_64-pc-windows-msvc",
    "architecture": {{
      "64bit": {{
        "url": "https://github.com/wrightkit/wright/releases/download/v$version/wright-$version-x86_64-pc-windows-msvc.zip"
      }}
    }}
  }}
}}
"""


def generate(version: str, hashes: dict, out_dir: Path) -> list:
    """Write every distribution manifest for `version` into `out_dir`.

    Returns the list of written paths (relative to out_dir).
    """
    for key, value in hashes.items():
        if value and not valid_hash(value):
            raise SystemExit(f"invalid sha256 for {key}: {value!r}")
    hashes = {key: (hashes.get(key) or PLACEHOLDER_HASH) for key in TARGETS}

    written = []

    formula = out_dir / "dist" / "homebrew" / "wright.rb"
    formula.parent.mkdir(parents=True, exist_ok=True)
    formula.write_text(homebrew_formula(version, hashes))
    written.append(formula.relative_to(out_dir))

    package_dir = out_dir / "dist" / "winget" / "manifests" / "w" / "WrightKit" / "Wright"
    if package_dir.is_dir():
        for stale in package_dir.iterdir():
            if stale.is_dir() and stale.name != version:
                shutil.rmtree(stale)
    version_dir = package_dir / version
    version_dir.mkdir(parents=True, exist_ok=True)
    winget_files = {
        f"WrightKit.Wright.installer.yaml": winget_installer(version, hashes["windows-x64"]),
        "WrightKit.Wright.locale.en-US.yaml": winget_default_locale(version),
        "WrightKit.Wright.yaml": winget_version(version),
    }
    for name, content in winget_files.items():
        (version_dir / name).write_text(content)
        written.append((version_dir / name).relative_to(out_dir))

    scoop = out_dir / "dist" / "scoop" / "wright.json"
    scoop.parent.mkdir(parents=True, exist_ok=True)
    scoop.write_text(scoop_manifest(version, hashes["windows-x64"]))
    written.append(scoop.relative_to(out_dir))

    return written


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", required=True, help="Wright version to generate metadata for")
    for target in TARGETS:
        parser.add_argument(f"--{target}-hash", default="", help=f"sha256 of the {target} release archive")
    parser.add_argument("--out-dir", type=Path, default=REPO_ROOT, help="output root (default: repository root)")
    args = parser.parse_args()

    version = version_from_tag(args.version)
    if not valid_hash(PLACEHOLDER_HASH):
        raise SystemExit("internal error: placeholder hash must be 64 hex chars")
    hashes = {target: getattr(args, f"{target.replace('-', '_')}_hash") for target in TARGETS}

    written = generate(version, hashes, args.out_dir)
    for path in written:
        print(f"generated {path}")
    print(f"done: {version}")


if __name__ == "__main__":
    main()
